pq.data = {};

// TODO: include a real generator
pq.data.names = [
  "gantar", "ailuin", "kyrtaar", "anfalen", "morthil", "folmon", "estelar",
  "gorwin", "lashul", "yhendorn", "sumia", "aerilaya", "lymsleia",
  "lusherina", "zaleria", "isilynor", "nephenee", "raejiisa", "zyrael",
  "ellarian", "tannyll", "ryul", "riluaneth", "marlevaur", "delsaran",
  "tanithil", "folmer", "alinar", "folduin", "lysanthir", "radelia",
  "amlaruil", "penelo", "nithenoel", "sarya", "rania", "tanelia",
  "myriani", "jhiilsraa"
];

pq.data.titles = [
  "brave", "concilliator", "mediator", "angry", "just", "fair", "powerful",
  "chaotic", "wise", "strong", "calm", "red", "veangeful", "mighty",
  "merciful", "lucky", "quick", "tall", "younger", "elder", "stout",
  "free", "strange", "bold", "relentless", "green", "thoughtful",
  "wild", "true", "deep", "far-sighted", "ever-ready", "loud",
  "friendly", "kind", "deep", "sage", "scourge", "redeemer",
  "skilled", "subtle", "proud", "fearless", "steady"
];

pq.data.gendercats = ["female", "male", "neutral"];

pq.data.pronouns = {
  "female": ["she/her/hers"],
  "male": ["he/him/his"],
  "neutral": [
    "they/them/their",
    "ey/em/eir", "hu/hum/hus", "per/per/per", "thon/thon/thons",
    "jee/jem/jeir", "ve/ver/vis",
    "xe/xem/xyr", "ze/zem/zes", "ze/hir/hir", "ze/mer/zer"
  ]
};

pq.data.genders = {
  "female": ["cis woman", "trans woman"],
  "male": ["cis man", "trans man"],
  "neutral": [
    "agender", "androgyne", "bigender", "boi", "demiboy", "demigirl", "enby",
    "genderfluid", "genderqueer", "intersex", "neutrosis", "pangender",
    "trans", "two-spirit", "epicene"
  ]
};

pq.data.professions = [
  "barbarian", "destroyer", "dragoon",
  "warrior", "fighter", "knight", "paladin", "ranger",
  "wizard", "sorceror", "witch", "warlock", "magician",
  "druid", "cleric", "priest", "shaman", "monk",
  "scout", "thief", "rogue", "bard", "archer", "ninja",
  "psion", "mutant"
];

pq.data.slots = [
  "head", "face", "ears", "neck",
  "torso", "back", "waist",
  "wrists", "hands", "finger",
  "legs", "feet"
];

pq.data.objects = [
  // weapons
  {"name": "halberd", "kind": "weapon"},
  {"name": "battle axe", "kind": "weapon"},
  {"name": "war hammer", "kind": "weapon"},
  {"name": "morning star", "kind": "weapon"},
  {"name": "mace", "kind": "weapon"},
  {"name": "club", "kind": "weapon"},
  {"name": "quarterstaff", "kind": "weapon"},
  {"name": "spiked chain", "kind": "weapon"},
  {"name": "bastard sword", "kind": "weapon"},
  {"name": "longsword", "kind": "weapon"},
  {"name": "broadsword", "kind": "weapon"},
  {"name": "saber", "kind": "weapon"},
  {"name": "cutlass", "kind": "weapon"},
  {"name": "rapier", "kind": "weapon"},
  {"name": "dagger", "kind": "weapon"},
  {"name": "switchblade", "kind": "weapon"},
  {"name": "pike", "kind": "weapon"},
  {"name": "harpoon", "kind": "weapon"},
  {"name": "spear", "kind": "weapon"},
  {"name": "javelin", "kind": "weapon"},
  {"name": "crossbow", "kind": "weapon"},
  {"name": "longbow", "kind": "weapon"},
  {"name": "knitting needles", "kind": "weapon"},
  {"name": "crochet hooks", "kind": "weapon"},
  {"name": "loom", "kind": "weapon"},
  {"name": "sewing machine", "kind": "weapon"},
  {"name": "typewriter", "kind": "weapon"},
  {"name": "laptop", "kind": "weapon"},
  {"name": "microphone", "kind": "weapon"},
  {"name": "lute", "kind": "weapon"},
  {"name": "harp", "kind": "weapon"},
  {"name": "keytar", "kind": "weapon"},
  {"name": "guitar", "kind": "weapon"},
  {"name": "bass", "kind": "weapon"},
  {"name": "drums", "kind": "weapon"},
  {"name": "camera", "kind": "weapon"},
  {"name": "lasso", "kind": "weapon"},
  {"name": "broomstick", "kind": "weapon"},
  {"name": "sharpie", "kind": "weapon"},
  {"name": "mechanical pencil", "kind": "weapon"},
  {"name": "bandsaw", "kind": "weapon"},
  {"name": "megaphone", "kind": "weapon"},
  {"name": "video camera", "kind": "weapon"},
  {"name": "labelmaker", "kind": "weapon"},
  {"name": "hula hoop", "kind": "weapon"},
  {"name": "synthesizer", "kind": "weapon"},
  {"name": "hedge shears", "kind": "weapon"},
  {"name": "violin", "kind": "weapon"},
  {"name": "viola", "kind": "weapon"},
  {"name": "cello", "kind": "weapon"},
  {"name": "french horn", "kind": "weapon"},
  {"name": "airhorn", "kind": "weapon"},
  {"name": "bag of glitter", "kind": "weapon"},
  {"name": "boom-box", "kind": "weapon"},
  {"name": "baton", "kind": "weapon"},
  {"name": "whistle", "kind": "weapon"},
  {"name": "subwoofer", "kind": "weapon"},
  {"name": "spraycan", "kind": "weapon"},

  // armor, head
  {"name": "crown", "kind": "armor", "slot": "head"},
  {"name": "du-rag", "kind": "armor", "slot": "head"},
  {"name": "comb", "kind": "armor", "slot": "head"},
  {"name": "tiara", "kind": "armor", "slot": "head"},
  {"name": "helm", "kind": "armor", "slot": "head"},
  {"name": "hat", "kind": "armor", "slot": "head"},
  {"name": "baseball cap", "kind": "armor", "slot": "head"},
  {"name": "headband", "kind": "armor", "slot": "head"},
  {"name": "stocking cap", "kind": "armor", "slot": "head"},
  {"name": "cowboy hat", "kind": "armor", "slot": "head"},
  {"name": "beret", "kind": "armor", "slot": "head"},
  {"name": "bike helmet", "kind": "armor", "slot": "head"},
  {"name": "circlet", "kind": "armor", "slot": "head"},
  {"name": "tricorne", "kind": "armor", "slot": "head"},

  // armor, face
  {"name": "spectacles", "kind": "armor", "slot": "face"},
  {"name": "glasses", "kind": "armor", "slot": "face"},
  {"name": "goggles", "kind": "armor", "slot": "face"},
  {"name": "headband", "kind": "armor", "slot": "face"},
  {"name": "bandana", "kind": "armor", "slot": "face"},
  {"name": "snorkel", "kind": "armor", "slot": "face"},
  {"name": "gas mask", "kind": "armor", "slot": "face"},
  {"name": "ski mask", "kind": "armor", "slot": "face"},

  // armor, ears
  {"name": "earrings", "kind": "armor", "slot": "ears"},
  {"name": "earmuffs", "kind": "armor", "slot": "ears"},
  {"name": "earplugs", "kind": "armor", "slot": "ears"},
  {"name": "earbuds", "kind": "armor", "slot": "ears"},
  {"name": "headphones", "kind": "armor", "slot": "ears"},

  // armor, neck
  {"name": "scarf", "kind": "armor", "slot": "neck"},
  {"name": "amulet", "kind": "armor", "slot": "neck"},
  {"name": "pendant", "kind": "armor", "slot": "neck"},
  {"name": "necklace", "kind": "armor", "slot": "neck"},
  {"name": "neckerchief", "kind": "armor", "slot": "neck"},
  {"name": "dog collar", "kind": "armor", "slot": "neck"},
  {"name": "spiked collar", "kind": "armor", "slot": "neck"},
  {"name": "bowtie", "kind": "armor", "slot": "neck"},
  {"name": "garland", "kind": "armor", "slot": "neck"},
  {"name": "choker", "kind": "armor", "slot": "neck"},

  // armor, finger
  {"name": "ring", "kind": "armor", "slot": "finger"},
  {"name": "magic ring", "kind": "armor", "slot": "finger"},
  {"name": "signet ring", "kind": "armor", "slot": "finger"},
  {"name": "decoder ring", "kind": "armor", "slot": "finger"},
  {"name": "nfc chip", "kind": "armor", "slot": "finger"},
  {"name": "knuckle tattoo", "kind": "armor", "slot": "finger"},
  {"name": "nail polish", "kind": "armor", "slot": "finger"},

  // armor, wrists
  {"name": "watch", "kind": "armor", "slot": "wrists"},
  {"name": "calculator watch", "kind": "armor", "slot": "wrists"},
  {"name": "swatch", "kind": "armor", "slot": "wrists"},
  {"name": "gel bracelets", "kind": "armor", "slot": "wrists"},
  {"name": "bracelet", "kind": "armor", "slot": "wrists"},
  {"name": "leather cuffs", "kind": "armor", "slot": "wrists"},
  {"name": "cuff links", "kind": "armor", "slot": "wrists"},
  {"name": "bracers", "kind": "armor", "slot": "wrists"},

  // armor, torso
  {"name": "denim jacket", "kind": "armor", "slot": "torso"},
  {"name": "t-shirt", "kind": "armor", "slot": "torso"},
  {"name": "vest", "kind": "armor", "slot": "torso"},
  {"name": "tank top", "kind": "armor", "slot": "torso"},
  {"name": "turtleneck", "kind": "armor", "slot": "torso"},
  {"name": "old sweater", "kind": "armor", "slot": "torso"},
  {"name": "plaid shirt", "kind": "armor", "slot": "torso"},

  // armor, back
  {"name": "cloak", "kind": "armor", "slot": "back"},
  {"name": "cape", "kind": "armor", "slot": "back"},
  {"name": "knapsack", "kind": "armor", "slot": "back"},
  {"name": "shawl", "kind": "armor", "slot": "back"},
  {"name": "wings", "kind": "armor", "slot": "back"},
  {"name": "messenger bag", "kind": "armor", "slot": "back"},
  {"name": "backpack", "kind": "armor", "slot": "back"},
  {"name": "banner", "kind": "armor", "slot": "back"},

  // armor, waist
  {"name": "belt", "kind": "armor", "slot": "waist"},
  {"name": "tool belt", "kind": "armor", "slot": "waist"},
  {"name": "utility belt", "kind": "armor", "slot": "waist"},
  {"name": "spiked belt", "kind": "armor", "slot": "waist"},
  {"name": "climbing harness", "kind": "armor", "slot": "waist"},
  {"name": "fanny pack", "kind": "armor", "slot": "waist"},
  {"name": "wallet chain", "kind": "armor", "slot": "waist"},

  // armor, hands
  {"name": "gloves", "kind": "armor", "slot": "hands"},
  {"name": "gauntlets", "kind": "armor", "slot": "hands"},
  {"name": "mittens", "kind": "armor", "slot": "hands"},
  {"name": "fingerless gloves", "kind": "armor", "slot": "hands"},
  {"name": "work gloves", "kind": "armor", "slot": "hands"},
  {"name": "rubber gloves", "kind": "armor", "slot": "hands"},

  // armor, legs
  {"name": "stonewashed jeans", "kind": "armor", "slot": "legs"},
  {"name": "cargo pants", "kind": "armor", "slot": "legs"},
  {"name": "cutoff shorts", "kind": "armor", "slot": "legs"},
  {"name": "skirt", "kind": "armor", "slot": "legs"},
  {"name": "denim skirt", "kind": "armor", "slot": "legs"},
  {"name": "tight pants", "kind": "armor", "slot": "legs"},
  {"name": "utility kilt", "kind": "armor", "slot": "legs"},
  {"name": "fishnets", "kind": "armor", "slot": "legs"},
  {"name": "yoga pants", "kind": "armor", "slot": "legs"},

  // armor, feet
  {"name": "sneakers", "kind": "armor", "slot": "feet"},
  {"name": "running shoes", "kind": "armor", "slot": "feet"},
  {"name": "clogs", "kind": "armor", "slot": "feet"},
  {"name": "slippers", "kind": "armor", "slot": "feet"},
  {"name": "sandals", "kind": "armor", "slot": "feet"},
  {"name": "wingtips", "kind": "armor", "slot": "feet"},
  {"name": "anklet", "kind": "armor", "slot": "feet"},
  {"name": "hiking boots", "kind": "armor", "slot": "feet"},
  {"name": "combat boots", "kind": "armor", "slot": "feet"},

  // transport
  {"name": "fixed gear bike", "kind": "transport"},
  {"name": "mountain bike", "kind": "transport"},
  {"name": "road bike", "kind": "transport"},
  {"name": "mutant bike", "kind": "transport"},
  {"name": "cross bike", "kind": "transport"},
  {"name": "cruiser bike", "kind": "transport"},
  {"name": "roller skates", "kind": "transport"},
  {"name": "roller blades", "kind": "transport"},
  {"name": "skateboard", "kind": "transport"},
  {"name": "moped", "kind": "transport"},
  {"name": "motorcycle", "kind": "transport"},
  {"name": "hearse", "kind": "transport"},
  {"name": "school bus", "kind": "transport"},
  {"name": "hybrid car", "kind": "transport"},
  {"name": "jalopy", "kind": "transport"},
  {"name": "tour van", "kind": "transport"},
  {"name": "scooter", "kind": "transport"},
  {"name": "biodiesel truck", "kind": "transport"},
  {"name": "pony", "kind": "transport"},
  {"name": "shopping cart", "kind": "transport"},

  // food
  {"name": "cupcake", "kind": "food"},
  {"name": "chapstick", "kind": "food"},
  {"name": "earl grey tea", "kind": "food"},
  {"name": "iced tea", "kind": "food"},
  {"name": "herbal tea", "kind": "food"},
  {"name": "oolong tea", "kind": "food"},
  {"name": "espresso", "kind": "food"},
  {"name": "coffee", "kind": "food"},
  {"name": "cheap beer", "kind": "food"},
  {"name": "craft beer", "kind": "food"},
  {"name": "whiskey", "kind": "food"},
  {"name": "diet soda", "kind": "food"},
  {"name": "soda", "kind": "food"},
  {"name": "potion", "kind": "food"},
  {"name": "elixir", "kind": "food"},
  {"name": "kale", "kind": "food"},
  {"name": "kambucha", "kind": "food"},
  {"name": "kombucha", "kind": "food"},
  {"name": "trail mix", "kind": "food"},
  {"name": "tincture", "kind": "food"},
  {"name": "beans", "kind": "food"},
  {"name": "doughnut", "kind": "food"},
  {"name": "frozen peas", "kind": "food"},
  {"name": "granola", "kind": "food"},
  {"name": "jam", "kind": "food"},
  {"name": "pickles", "kind": "food"},
  {"name": "ice cream", "kind": "food"},
  {"name": "microgreens", "kind": "food"},
  {"name": "basil", "kind": "food"},
  {"name": "rhubarb", "kind": "food"},
  {"name": "string cheese", "kind": "food"},

  // item
  {"name": "slingshot organizer", "kind": "item"},
  {"name": "journal", "kind": "item"},
  {"name": "fanzine", "kind": "item"},
  {"name": "zine", "kind": "item"},
  {"name": "show flyer", "kind": "item"},
  {"name": "notebook", "kind": "item"},
  {"name": "polyhedral dice", "kind": "item"},
  {"name": "iww membership card", "kind": "item"},
  {"name": "stickers", "kind": "item"},
  {"name": "smartphone", "kind": "item"},
  {"name": "lighter", "kind": "item"},
  {"name": "twitter account", "kind": "item"},
  {"name": "tumblr account", "kind": "item"},
  {"name": "metro pass", "kind": "item"},
  {"name": "ball of yarn", "kind": "item"},
  {"name": "tarot cards", "kind": "item"},
  {"name": "record crate", "kind": "item"},
  {"name": "mix tape", "kind": "item"},
  {"name": "mp3 player", "kind": "item"},
  {"name": "cell phone", "kind": "item"},
  {"name": "bus token", "kind": "item"},
  {"name": "purse", "kind": "item"},
  {"name": "pocketbook", "kind": "item"},
  {"name": "guitar pick", "kind": "item"},
  {"name": "sketchbook", "kind": "item"},
  {"name": "stickynotes", "kind": "item"},
  {"name": "flashlight", "kind": "item"},
  {"name": "floss", "kind": "item"},
  {"name": "flare", "kind": "item"},
  {"name": "dye", "kind": "item"},
  {"name": "ultraslime", "kind": "item"},
  {"name": "teapot", "kind": "item"},
];

pq.data.effects = {};

pq.data.effects.armor = [
  "_ of shadow",
  "_ of flame",
  "_ of frost",
  "_ of lightning",
  "_ of stone",
  "_ of invulnerability",
  "_ of quickness",
  "_ of power",
  "_ of the wolf",
  "elven _",
  "dwarven _",
  "cursed _",
  "mighty _",
  "dire _",
  "_ of the gods",
  "holy _",
  "unholy _",
  "secular _",
  "_ of light",
  "_ of protection",
  "silver _",
  "golden _",
  "mithril _",
  "_ of strength",
  "masterwork _",
  "_ of enchantment",
  "legendary _",
  "ancient _",
  "forbidden _",
  "lunar _",
  "solar _",
  "cosmic _",
  "secret _",
  "crystal _",
  "vorpal _",
  "_ of sharpness",
  "_ of speed",
  "subtle _",
  "spiked _",
  "sharp _",
  "glowing _",
  "_ of the stars",
  "_ of pain",
  "_ of wounding",
  "_ of accuracy",
  "_ (defender)",
  "_ of beauty",
  "_ of truth",
  "_ of submission",
  "_ of intersubjectivity",
  "critical _",
  "textual _",
  "intersectional _",
  "postmodern _",
  "semiotic _",
  "_ of critique",
  "theoretical _",
  "_ of détournement",
  'insult-resistant _',
];

pq.data.effects.wprefix = {
  'normal': [
    'occult _',
    'mystical _',
    'obsidian _',
    'ruby _',
    'sapphire _',
    'emerald _',
    'opalescent _',
    'singing _',
    'crushing _',
    'consecrated _',
    'spiteful _',
    'reverberating _',
    'dazzling _',
    'haunted _',
    'runic _',
    'enchanted',
    'electrifying _',
    'elven _',
    'dwarven _',
    'unholy _',
    'holy _',
    'flaming _',
    'chilling _',
    'thunderous _',
    'cleaving _',
    'telepathic _',
    'barbaric _',
    'nightmarish _',
    'treacherous _',
    'druidic _',
    'psionic _',
    'masterwork _',
    'hypnotic _',
    'mighty _',
    'keen _',
    'withering _',
    'icy _',
    'searing _',
    'brutal _',
    'destructive _',
    'knightly _',
    'tricky _',
    'military-grade _',
    'nimble _',
    'monstrous _',
    'shadowy _',
    'martial _',
    'arcane _',
  ],
  'heroic': [
    'otherworldly _',
    'divine _',
    'malignant _',
    'necro-_',
    'electro-_',
    'pyro-_',
    'aero-_',
    'geo-_',
    'prismatic _',
    'miraculous _',
    'anti-racist _',
    'feminist _',
    'hexing _',
    'double-_',
    'fabulous _',
    'gamer-bane _',
    'bro-bane _',
    'reddit-bane _',
    'anarchic _',
    'socialist _',
    'glitching _',
    'ethereal _',
    'witch-made _',
    'capitalist-bane _',
    'adamantine _',
    'darkwood _',
    'pragmatic _',
    'vorpal _',
    'chainbreaking _',
    'liberating _',
    'revolutionary _',
    'marxist _',
    'matriarchal _',
    'anti-fascist _',
    'anti-patriarchy _',
    'forbidden _',
    'uniting _',
    'partially virtual _',
    'demon-forged _',
    'axiomatic _',
    'chaotic _',
    'subversive _',
    'demolishing _',
    'celestial _',
    'infernal _',
    'umbral _',
    'penumbral _',
  ],
  'epic': [
    'eldritch _',
    'never-missing _',
    'cosmic _',
    'communist _',
    'intersectional _',
    'star-forged _',
    'interphasic _',
    'theoretical _',
    'semiotic _',
    'transcultural _',
    'insurrectionary _',
    'anti-kyriarchy _',
    'hyperreal _',
    'pangender _',
    'non-deterministic _',
    'deconstructing _',
    'non-euclidean _',
    'metacognizant _',
    'neutronium _',
    'quantum _',
    'perfect _',
    'awe-inspiring _',
    'heroic _',
    'transnational _',
    'ascendant _',
    'paragon-_',
    'venusian _',
    'nanotech _',
    'cytherean _',
    'hermetic _',
    'alchemical _',
    'draconic _',
    'indestructible _',
    'gaean _',
    'pan-cosmic _',
    'thousandfold _',
    'xentronium _',
    'titanic _',
    'all-conquering _',
    'transinfinite _',
    'omnipotent _',
    'omniscient _',
    'eternal _',
    'future-writing _',
    'obliterating _',
    'the last, best _',
    'primordial _',
  ],
}

pq.data.effects.wsuffix = {
  'normal': [
    '_ of air',
    '_ of the cat',
    '_ of ruination',
    '_ of fortune',
    '_ of mystery',
    '_ of potency',
    '_ of the centaur',
    '_ of the wind',
    '_ of whirlpool',
    '_ of tornados',
    '_ of strength',
    '_ of cunning',
    '_ of quickness',
    '_ of blood',
    '_ of spirits',
    '_ of explosions',
    '_ of discipline',
    '_ of the elements',
    '_ of terror',
    '_ of the wild',
    '_ of the wolf',
    '_ of the bear',
    '_ of the owl',
    '_ of ice',
    '_ of thunder',
    '_ of thunderbolts',
    '_ of deftness',
    '_ of the moon',
    '_ of confusion',
    '_ of courage',
    '_ of illumination',
    '_ of brilliance',
    '_ from outer space',
    '_ of shocking',
    '_ of fury',
    '_ of justice',
    '_ of fire',
    '_ of ice',
    '_ of lightning',
    '_ of the black arts',
    '_ of necromancy',
    '_ of destiny',
    '_ of magma',
    '_ of lava',
    '_ of turmoil',
    '_ of love',
    '_ of the sky',
  ],
  'heroic': [
    '_ of the dark fire',
    '_ of the lion',
    '_ of the octopus',
    '_ of dark rituals',
    '_ power overwhelming',
    '_ of foe-smiting',
    '_ of impaling',
    '_ of draining',
    '_ of glass',
    '_ of the deep',
    '_ of worms',
    '_ of the volcano',
    '_ of savagery',
    '_ of fate',
    '_ of pestilence',
    '_ of hunger',
    '_ of the vampire',
    '_ of the wraith',
    '_ of the sabertooth tiger',
    '_ of the elephant',
    '_ of the shark',
    '_ of the elder gods',
    '_ of psychic domination',
    '_ of backstabbing',
    '_ of heroism',
    '_ of the grotesque',
    '_ of genderfluidity',
    '_ of the sun',
    '_ of the oppressed',
    '_ of anti-misogyny',
    '_ of male tears',
    '_ of veganism',
    '_ of smiting',
    '_ of endless progression',
    '_ of the meek',
    '_ of justice',
    '_ of wisdom',
    '_ of dreams',
    '_ of the people',
    '_ of the rose',
    '_ of destruction',
    '_ of orchids',
    '_ of earthquakes',
    '_ of tsunamis',
    '_ of conflagration',
    '_ of tempests',
    '_ of secrets',
  ],
  'epic': [
    '_ of the void',
    '_ of the world serpent',
    '_ of the dragon',
    '_ of the primordial gods',
    '_ of the ancient ones',
    '_ of the sacred power',
    '_ of truth',
    '_ of the lich',
    '_ of the demilich',
    '_ of the dracolich',
    '_ of metaphysics',
    '_ of epistemology',
    '_ of ethics',
    '_ of criticism',
    '_ of supreme victory',
    '_ of dissent',
    '_ of nationalization',
    '_ of economic justice',
    '_ of social justice',
    '_ of racial justice',
    '_ of equality',
    '_ of the kraken',
    '_ of humiliation',
    '_ of the zodiac',
    '_ of doom',
    '_ from the year 3014',
    '_ of absolute zero',
    '_ of infinity',
    '_ of annihilation by love',
    '_ of collective consciousness',
    '_ of legend',
    '_ of vortices',
    '_ of the planet',
    '_ of the world-storm',
    '_ of spacetime',
    '_ of pure creation',
    '_ of amaranth',
    '_ of spheres beyond imagining',
    '_ that uplifts all',
    '_ of eternal love',
    '_ of eternal friendship',
    '_ of unbreakable bonds',
    '_ of inextinguishable light',
    '_ of universal hope',
    '_ of unimpeachable authority',
    '_ of inviolable sanctuary',
    '_ of absolute kindness',
    '_ of apocalypse and rebirth',
    '_ of the immortals',
    '_ from beyond time and space',
  ],
};

pq.data.effects.food = [
  "_ of healing",
  "_ of protection",
  "_ of barkskin",
  "_ of wisdom",
  "_ of critique",
  "_ of invisibility",
  "_ of displacement",
  "_ of flight",
  "_ of heroism",
  "_ of analysis",
  "_ of discourse",
  "_ of rage",
  "_ of poison",
  "_ of magic",
  "_ of darkness",
  "_ of sleep",
  "_ of cure disease",
  "_ of enlightenment",
  "_ of augmentation",
  "_ of charisma",
  "_ of strength",
  "heroic _",
  "blessed _",
];

pq.data.foes = {
  0: [
    {"name": "youtube commenter", "faction": "*", "lvl": 1},
    {"name": "gamer", "faction": "*", "lvl": 1},
    {"name": "goblin", "faction": "*", "lvl": 1},
    {"name": "bro", "faction": "*", "lvl": 1},
    {"name": "chucker", "faction": "*", "lvl": 1},
    {"name": "game", "faction": "*", "lvl": 1},
    {"name": "manbaby", "faction": "*", "lvl": 1},
    {"name": "zombie", "faction": "*", "lvl": 1},
    {"name": "creep", "faction": "*", "lvl": 1},
  ],
  1: [
    {"name": "ignoramus", "faction": "*", "lvl": 1},
    {"name": "mall ninja", "faction": "*", "lvl": 1},
    {"name": "redditor", "faction": "*", "lvl": 1},
    {"name": "hobgoblin", "faction": "*", "lvl": 1},
    {"name": "manchild", "faction": "*", "lvl": 1},
    {"name": "tech bro", "faction": "*", "lvl": 1},
    {"name": "sketcher", "faction": "*", "lvl": 1},
    {"name": "lurker", "faction": "*", "lvl": 1},
    {"name": "explainer", "faction": "*", "lvl": 1},
    {"name": "tea partier", "faction": "*", "lvl": 1},
    {"name": "dogpiler", "faction": "*", "lvl": 1},
    {"name": "sea lion", "faction": "*", "lvl": 1},
  ],
  2: [
    {"name": "rando", "faction": "*", "lvl": 1},
    {"name": "fake account", "faction": "*", "lvl": 1},
    {"name": "gelatinous tetrahedron", "faction": "*", "lvl": 1},
    {"name": "/b/er", "faction": "*", "lvl": 1},
    {"name": "bugbear", "faction": "*", "lvl": 1},
    {"name": "nice guy", "faction": "*", "lvl": 1},
    {"name": "screed author", "faction": "*", "lvl": 1},
    {"name": "condescender", "faction": "*", "lvl": 1},
    {"name": "sock-puppet", "faction": "*", "lvl": 1},
    {"name": "moderate", "faction": "*", "lvl": 1},
  ],
  3: [
    {"name": "harasser", "faction": "*", "lvl": 1},
    {"name": "/v/er", "faction": "*", "lvl": 1},
    {"name": "good old boy", "faction": "*", "lvl": 1},
    {"name": "neoconfederate", "faction": "*", "lvl": 1},
    {"name": "pick up artist", "faction": "*", "lvl": 1},
    {"name": "mouth breather", "faction": "*", "lvl": 1},
    {"name": "misogynist", "faction": "*", "lvl": 1},
    {"name": "grammarian", "faction": "*", "lvl": 1},
    {"name": "birther", "faction": "*", "lvl": 1},
    {"name": "clickbaiter", "faction": "*", "lvl": 1},
  ],
  4: [
    {"name": "gelatinous cube", "faction": "*", "lvl": 1},
    {"name": "wererat", "faction": "*", "lvl": 1},
    {"name": "doxxer", "faction": "*", "lvl": 1},
    {"name": "homophobe", "faction": "*", "lvl": 1},
    {"name": "transphobe", "faction": "*", "lvl": 1},
    {"name": "anti-vaxer", "faction": "*", "lvl": 1},
    {"name": "correctionary", "faction": "*", "lvl": 1},
    {"name": "trogolodyte", "faction": "*", "lvl": 1},
    {"name": "men's rights activist", "faction": "*", "lvl": 1},
    {"name": "ghoul", "faction": "*", "lvl": 1},
    {"name": "manarchist", "faction": "*", "lvl": 1},
    {"name": "tone police officer", "faction": "*", "lvl": 1},
    {"name": "brocialist", "faction": "*", "lvl": 1},
    {"name": "yuppie", "faction": "*", "lvl": 1},
  ],
  5: [
    {"name": "politician", "faction": "*", "lvl": 1},
    {"name": "owlbear", "faction": "*", "lvl": 1},
    {"name": "stalker", "faction": "*", "lvl": 1},
    {"name": "landlord", "faction": "*", "lvl": 1},
    {"name": "script kiddie", "faction": "*", "lvl": 1},
    {"name": "essentialist", "faction": "*", "lvl": 1},
    {"name": "racist", "faction": "*", "lvl": 1},
    {"name": "apologist", "faction": "*", "lvl": 1},
    {"name": "derailer", "faction": "*", "lvl": 1},
    {"name": "pedant", "faction": "*", "lvl": 1},
    {"name": "male gazer", "faction": "*", "lvl": 1},
    {"name": "ghast", "faction": "*", "lvl": 1},
    {"name": "gold bug", "faction": "*", "lvl": 1},
    {"name": "cop", "faction": "*", "lvl": 1},
    {"name": "contractor", "faction": "*", "lvl": 1},
  ],
  6: [
    {"name": "gelatinous octahedron", "faction": "*", "lvl": 1},
    {"name": "slumlord", "faction": "*", "lvl": 1},
    {"name": "werewolf", "faction": "*", "lvl": 1},
    {"name": "spook", "faction": "*", "lvl": 1},
    {"name": "xenophobe", "faction": "*", "lvl": 1},
    {"name": "jingoist", "faction": "*", "lvl": 1},
    {"name": "skeptic", "faction": "*", "lvl": 1},
    {"name": "wight supremacist", "faction": "*", "lvl": 1},
    {"name": "contrarian", "faction": "*", "lvl": 1},
    {"name": "scumbag", "faction": "*", "lvl": 1},
    {"name": "troll", "faction": "*", "lvl": 1},
    {"name": "techno-utopian", "faction": "*", "lvl": 1},
    {"name": "entrepreneur", "faction": "*", "lvl": 1},
  ],
  7: [
    {"name": "scab", "faction": "*", "lvl": 1},
    {"name": "capitalist", "faction": "*", "lvl": 1},
    {"name": "informant", "faction": "*", "lvl": 1},
    {"name": "bigot", "faction": "*", "lvl": 1},
    {"name": "concern troll", "faction": "*", "lvl": 1},
    {"name": "tory", "faction": "*", "lvl": 1},
    {"name": "republican", "faction": "*", "lvl": 1},
    {"name": "democrat", "faction": "*", "lvl": 1},
    {"name": "flag-waver", "faction": "*", "lvl": 1},
    {"name": "defacer", "faction": "*", "lvl": 1},
  ],
  8: [
    {"name": "gelatinous dodecahedron", "faction": "*", "lvl": 1},
    {"name": "hippogryph", "faction": "*", "lvl": 1},
    {"name": "liberal", "faction": "*", "lvl": 1},
    {"name": "conservative", "faction": "*", "lvl": 1},
    {"name": "ukipper", "faction": "*", "lvl": 1},
    {"name": "venture capitalist", "faction": "*", "lvl": 1},
    {"name": "fundamentalist", "faction": "*", "lvl": 1},
    {"name": "war hawk", "faction": "*", "lvl": 1},
    {"name": "crypto-eugenicist", "faction": "*", "lvl": 1},
    {"name": "impersonator", "faction": "*", "lvl": 1},
  ],
  9: [
    {"name": "mummy", "faction": "*", "lvl": 1},
    {"name": "social darwinist", "faction": "*", "lvl": 1},
    {"name": "grue", "faction": "*", "lvl": 1},
    {"name": "anarcho-capitalist", "faction": "*", "lvl": 1},
    {"name": "talk radio host", "faction": "*", "lvl": 1},
    {"name": "neofascist", "faction": "*", "lvl": 1},
    {"name": "griffon", "faction": "*", "lvl": 1},
    {"name": "rebuttalist", "faction": "*", "lvl": 1},
    {"name": "reaganite", "faction": "*", "lvl": 1},
    {"name": "thatcherite", "faction": "*", "lvl": 1},
    {"name": "abuser", "faction": "*", "lvl": 1},
  ],
  10: [
    {"name": "gelatinous icosahedron", "faction": "*", "lvl": 1},
    {"name": "primitivist", "faction": "*", "lvl": 1},
    {"name": "militia", "faction": "*", "lvl": 1},
    {"name": "neofeudalist", "faction": "*", "lvl": 1},
    {"name": "shock jock", "faction": "*", "lvl": 1},
    {"name": "xenomorph", "faction": "*", "lvl": 1},
    {"name": "rust monster", "faction": "*", "lvl": 1},
    {"name": "shambling mound", "faction": "*", "lvl": 1},
    {"name": "reactionary", "faction": "*", "lvl": 1},
    {"name": "bunker-dweller", "faction": "*", "lvl": 1},
    {"name": "oppressor", "faction": "*", "lvl": 1},
  ],
  11: [
    {"name": "militia captain", "faction": "*", "lvl": 1},
    {"name": "preacher", "faction": "*", "lvl": 1},
    {"name": "stormtrooper", "faction": "*", "lvl": 1},
    {"name": "meritocrat", "faction": "*", "lvl": 1},
    {"name": "vigilante", "faction": "*", "lvl": 1},
    {"name": "spambot", "faction": "*", "lvl": 1},
    {"name": "corrupt mod", "faction": "*", "lvl": 1},
    {"name": "land developer", "faction": "*", "lvl": 1},
    {"name": "manticore", "faction": "*", "lvl": 1},
    {"name": "libertarian", "faction": "*", "lvl": 1},
    {"name": "banker", "faction": "*", "lvl": 1},
    {"name": "marketer", "faction": "*", "lvl": 1},
  ],
  12: [
    {"name": "militia colonel", "faction": "*", "lvl": 1},
    {"name": "bitcoin miner", "faction": "*", "lvl": 1},
    {"name": "lobbyist", "faction": "*", "lvl": 1},
    {"name": "executive", "faction": "*", "lvl": 1},
    {"name": "financier", "faction": "*", "lvl": 1},
    {"name": "vampire", "faction": "*", "lvl": 1},
    {"name": "country club", "faction": "*", "lvl": 1},
    {"name": "world banker", "faction": "*", "lvl": 1},
    {"name": "media mogul", "faction": "*", "lvl": 1},
    {"name": "CFO", "faction": "*", "lvl": 1},
    {"name": "email marketer", "faction": "*", "lvl": 1},
  ],
  13: [
    {"name": "c-level executive", "faction": "*", "lvl": 1},
    {"name": "purple worm", "faction": "*", "lvl": 1},
    {"name": "captain of industry", "faction": "*", "lvl": 1},
    {"name": "techno-libertarian", "faction": "*", "lvl": 1},
    {"name": "lord of finance", "faction": "*", "lvl": 1},
    {"name": "petty tyrant", "faction": "*", "lvl": 1},
    {"name": "megachurch preacher", "faction": "*", "lvl": 1},
    {"name": "collaborator", "faction": "*", "lvl": 1},
    {"name": "election-rigger", "faction": "*", "lvl": 1},
    {"name": "spammer", "faction": "*", "lvl": 1},
  ],
  14: [
    {"name": "cash golem", "faction": "*", "lvl": 1},
    {"name": "wyvern", "faction": "*", "lvl": 1},
    {"name": "cyber-libertarian", "faction": "*", "lvl": 1},
    {"name": "randroid", "faction": "*", "lvl": 1},
    {"name": "premillenial dispensationalist", "faction": "*", "lvl": 1},
    {"name": "botnet", "faction": "*", "lvl": 1},
    {"name": "moral absolutist", "faction": "*", "lvl": 1},
    {"name": "wall street executive", "faction": "*", "lvl": 1},
    {"name": "bitcoin billionaire", "faction": "*", "lvl": 1},
    {"name": "media manipulator", "faction": "*", "lvl": 1},
  ],
  15: [
    {"name": "truther", "faction": "*", "lvl": 1},
    {"name": "climate change denier", "faction": "*", "lvl": 1},
    {"name": "strikebreaker", "faction": "*", "lvl": 1},
    {"name": "reptoid", "faction": "*", "lvl": 1},
    {"name": "CEO", "faction": "*", "lvl": 1},
    {"name": "torturer", "faction": "*", "lvl": 1},
    {"name": "hatemonger", "faction": "*", "lvl": 1},
    {"name": "kraken", "faction": "*", "lvl": 1},
    {"name": "dragon", "faction": "*", "lvl": 1},
    {"name": "objectivist", "faction": "*", "lvl": 1},
  ],
};

pq.data.ranks = {
  "-5": [
    'incoherent _',
    'sloppy _',
    'flailing _',
    'hilariously bad _',
    'abysmal _',
    'unworthy _',
    'necrotic _',
    'hexed _',
    '_-head-in-a-jar',
    'least-effective _',
    'moribund _',
  ],
  "-4": [
    'sleep-deprived _',
    'demoralized _',
    'rotting _',
    'inexperienced _',
    'minor _',
    'extremely drunk _',
    'insignificant _',
    'unmotivated _',
    'slouchy _',
  ],
  "-3": [
    'lesser _',
    'confused _',
    "young _",
    'easily distracted _',
    'sleepy _',
    'LOLing _',
    'convictionless _',
    'uninspired _',
  ],
  "-2": [
    'cursed _',
    'bored _',
    'slow-typing _',
    'novice _',
    'poseur _',
    'stumbling _',
    '_ with 5 followers',
    'talc _',
  ],
  "-1": [
    'drowsy _',
    '_ with a short attention span',
    'foolish _',
    'expletive obsessed _',
    'sore loser _',
    'drunk _',
    'copycat _',
    'meritless _',
  ],
  "0": [
    '_ on a bender',
    'edgy _',
    '_ wearing a burger king crown',
    '_ at brunch',
    '_ in a basement',
    'ROFLing _',
    'self-obsessed _',
  ],
  "1": [
    'advanced _',
    'zealous _',
    'desensitized _',
    'caffienated _',
    'incensed _',
    'infamous _',
    'unapologetic _',
    'fearless _',
    'sycophantic _',
  ],
  "2": [
    "greater _",
    '_ with keyboard macros',
    'armored _',
    'persistent _',
    '_ IN ALL CAPS',
    'sarcastic _',
    '_ who must always have the last word',
  ],
  "3": [
    '_-band',
    'elite _',
    '_ atop a throne',
    "'roided up _",
    'tricky _',
    'overcaffienated _',
    'apoplectic _',
    'curmudgeonly _',
    'unhygenic _',
    '_-hero',
    'feldspar _',
  ],
  "4": [
    "juicing _",
    "elder _",
    "two-headed _",
    "far-famed _",
    "skeletal _",
    'genuinely appalling _',
    "_ on a mission",
    "lock-step _",
    "venomous _",
    '_ in a car',
  ],
  "5": [
    '_-pack',
    'dire _',
    'augmented _',
    'very unhygenic _',
    'hardcore _',
    '_ with a boom-box',
    'tech-savvy _',
    '_ with too much time on his hands',
    '_-lord',
    'totally desensitized _',
    'quartz _',
    '_ who types extremely quickly',
  ],
  "6": [
    'orthodox _',
    '_ on a quest',
    'mutant _',
    'on-fire _',
    'subterranean _',
    'electro-_',
    'slime-_',
    'undead _',
    '_ with knowledge of logical fallacies',
    'unrelenting _',
    'relentless _',
    'unscrupulous _',
    'extremely profane _',
  ],
  "7": [
    '_-king',
    'giant _',
    'mad _',
    '_ with 10,000 followers',
    '_-gang',
    'plant-murdering _',
    'filth-drenched _',
    'kung-fu _',
    'ex-progressive _',
    'topaz _',
    '_ with seven mirror images',
    'undercover _',
    'cybernetic _',
  ],
  "8": [
    'corporate _',
    'adept _',
    '_ of fire',
    '_ of earth',
    '_ of water',
    '_ of air',
    '_ in a pickup truck',
    'empowered _',
    'abhorrent _',
    '_ covered in puke',
    'hypermacho _',
    'well-read _',
    'old-school _',
    '_ on a holy quest',
  ],
  "9": [
    'corundum _',
    'five-headed _',
    'gas-powered _',
    '_ with quad-damage',
    '_ of legend',
    '_-squadron',
    'gargantuan _',
    'insectoid _',
    '_ with 100,000 followers',
    'vile _',
    'explosive _',
    'half-robot _',
  ],
  "10": [
    '_ of ooze',
    '_ of smoke',
    '_ of ice',
    '_ of magma',
    'haunted _',
    'white power _',
    '_ in a humvee',
    'older-than-old-school _',
    '_ with government connections',
    'hyper-orthodox _',
    '_-army',
    'copper _',
    'many-bladed _',
    '_-guru',
  ],
  "11": [
    'diamond _',
    '_ with 500,000 followers',
    '_ of great power',
    'colossal _',
    '_-horde',
    'hive-mind _',
    'ghostly _',
    '_ covered in epithet runes',
    '_/hacker',
    '_ of the ethereal plane',
    'counter-revolutionary _',
    'steam-powered _',
    '_ with berserker rage',
    '_-hydra',
    '_ with a closet full of weapons',
  ],
  "12": [
    '_ of salt',
    '_ of vacuum',
    '_ of ash',
    '_ of dust',
    'ancient _',
    '_ in a tank',
    'graybeard _',
    'master _',
    '_-throng',
    'true believer _',
    'brass _',
    'tenfold-_',
    '_ of dreams and nightmares',
    'bronze _',
    'silver _',
    'gold _',
    '_ who speaks in walls of text',
  ],
  "13": [
    'nanotech _',
    '_ with one million followers',
    'infernal _',
    '_-swarm',
    'titanic _',
    'partially-ascended _',
    'non-corporeal _',
    '_ of the far realms',
    'diesel-powered _',
    '_ in a battleship',
    'hundred-handed _',
    '_ wielding a thousand slurs',
    '_ with a seventy-page manifesto',
  ],
  "14": [
    '_ of shadow',
    '_ of negative energy',
    '_ of the inferno',
    '_ of the deep',
    '_-avatar',
    'xenolithic _',
    'true-silver _',
    '_ in a floating fortress',
    'grand master _',
    'meta-cognizant _',
    'doomed _',
    'hate-crowned _',
    ],
  "15": [
    '_ legion',
    '_ with five million followers',
    '_ constellation',
    '_-demigod',
    'neutronium _',
    '_ with a five-hundred page manifesto',
    '_ from a dimension of hate',
    'adamantium _',
    'ubiquitous and nigh-ineradicable _',
    'supreme _',
    'worst-ever _',
  ],
};

pq.data.zones = {
  0: [
    'alley',
    'slum',
    'youtube',
    'tumblr',
    'car dealership',
    'forum',
    'mall',
    'sewer',
    'shantytown',
    'street corner',
    'gate',
    'basement',
  ],
  1: [
    'subreddit',
    'hashtag',
    'garden',
    'highrise',
    'strip mall',
    'golf course',
    'bunker',
    'gym',
    'factory',
    'gated community',
    'lan party',
    'quarter',
    'sub-basement',
  ],
  2: [
    'arcade',
    'mcmansion',
    'campus',
    'quarry',
    'mine',
    'parking lot',
    'diner',
    'underbridge',
    'facebook group',
    'highrise',
    'torrent aggregator',
    'airport',
    'freeway',
    'crawlspace',
  ],
  3: [
    'refuge',
    'stadium',
    'train',
    'skate park',
    'skyscraper',
    'bunker',
    'corporate headquarters',
    'irc channel',
    'bbs',
    'suburb',
    'meetup',
    'news website',
    'theater',
    'festival',
    'bank',
    'tunnel',
  ],
  4: [
    'darknet',
    'labyrinth',
    'wal-mart',
    'office park',
    'subway',
    'laboratory',
    'spa',
    'ski resort',
    'ranch',
    'convention center',
    'mansion',
    'spring',
    'slaughterhouse',
    'cave',
  ],
  5: [
    'everglade',
    'police station',
    'gaming convention',
    'aircraft carrier',
    'backwoods',
    'factory farm',
    'space station',
    'private island',
    'private jet',
    'manor',
    'arena',
    'echo chamber',
    'pothole',
  ],
  6: [
    'library',
    'wiki',
    'oil rig',
    'capitalist bookstore',
    'luxury-goods emporium',
    'casino',
    'castle',
    "debtors' prison",
    'stock exchange',
    'credit card company',
    'black market',
    'ziggurat',
    'necropolis',
    'princess cruise',
  ],
  7: [
    'image board',
    'MUD',
    'gulch',
    'arms dealer emporium',
    'fallout shelter',
    'ark',
    'techno-fortress',
    'floating city',
    'mirror labyrinth',
    'new world order',
    'empire',
    'mountaintop stronghold',
  ],
  8: [
    'MUSH',
    'asteroid',
    'parallel dimension',
    'abyss',
    'republican dream',
    'bio-dome',
    'sanctum',
    'marianas trench colony',
  ],
  9: [
    'platonic dominion',
    'city-planet',
    'spatial vortex',
    'time bubble',
    'pocket dimension',
    'world-tree',
    'post-apocalyptic wasteland',
  ],
  10: [
    'madness-made-real',
    'time before the big bang',
    'man-made eden',
    'clockwork nirvana',
    'fragment of the collective unconscious',
    'union of all possible realms',
  ],
};

pq.data.zonemods = {
  0: [
    'worrisome _',
    'distressing _',
    'abandoned _',
    'decaying _',
    'creepy _',
    'sketchy _',
    'smelly _',
    'unmaintained _',
    '_ covered in graffiti',
  ],
  1: [
    'dreary _',
    'bleak _',
    'defaced _',
    'cheap _',
    '_ riddled with defects',
    'gross _',
    'dusty _',
    'skeezy _',
    'smoky _',
    'tacky _',
  ],
  2: [
    'corrupt _',
    'desolate _',
    'private _',
    'oversized _',
    'executive _',
    '_ for the privileged',
    'mass-produced _',
    'waterfront _',
    '_ bedecked with gold',
    'opulent _',
    'exploitative _',
  ],
  3: [
    'buried _',
    'secret _',
    'shabby-chic _',
    'infested _',
    'contested _',
    'clear-cut _',
    'bought-out _',
    'sponsored _',
    'glamorous _',
    'concrete _',
    'plastic _',
    'password-protected _',
    'anarchist _',
  ],
  4: [
    '_ of war',
    '_ of shadows',
    'corporate _',
    'downsized _',
    'upscale _',
    'nefarious _',
    'egregious _',
    'silent _',
    'dread _',
    'looted _',
    'overgrown _',
    'flooded _',
    '_ where it never stops raining',
    'million-dollar _',
    'unfinished _',
    'unnerving _',
  ],
  5: [
    'sprawling _',
    '_-complex',
    'foetid _',
    'forsaken _',
    'horrifying _',
    'segregated _',
    '_ that only accepts company scrip',
    'nuclear _',
    'billion-dollar _',
    'ancient _',
    'blasphemous _',
    'monocultural _',
    '_ where identity is forbidden',
    'fear-driven _',
    'patriarchal _',
    'virulent _',
    'regressive _',
    'victimizing _',
    'raiding _',
    'frigid _',
    'lonely _',
  ],
  6: [
    'prehistoric _',
    'godless _',
    'lunar _',
    'petrified _',
    'undersea _',
    '_ built by unpaid labor',
    'heteronormative _',
    'trillion-dollar _',
    'vine-wrapped _',
    'masquerade _',
    'appropriated _',
    'fated _',
    'crowdfunded _',
    'decadent _',
    'joyless _',
    'sinking _',
    '_ of injustice',
    'conspiratorial _',
    'garbage-filled _',
    'lightless _',
    'grim _',
  ],
  7: [
    'extra-terrestrial _',
    'solid gold _',
    'thousand-acre _',
    '_ fit for a king',
    'impervious _',
    '_ inside a volcano',
    'jewel-encrusted _',
    'sunken _',
    'anonymous _',
    'hateful _',
    'supremacist _',
    'septic _',
    'leaderless _',
    'propaganda-strewn _',
    'unmoderated _',
    'unempathetic _',
    'militaristic _',
    'sunless _',
    'ephemeral _',
    'toxic _',
    '_ of enforced silence',
  ],
  8: [
    'time-shifted _',
    'bottomless _',
    'aberrant _',
    'convergent _',
    'demonic _',
    'pearly _',
    '_ immersed in microgravity',
    '_ ruled by goblins',
    'holographic _',
    'four-dimensional _',
    'immaterial _',
    'lost _',
    'fusion-powered _',
    '_ on a plane of shadow',
    '_ of maximum ethics',
    'fully-disclosed _',
    'wretched _',
    'skyless _',
    'encrypted _',
    'vorticular _',
    'nonphysical _',
  ],
  9: [
    'bizarre _',
    'erratic _',
    'ineffable _',
    '_ that cannot be named',
    'pan-dimensional _',
    'hyperborean _',
    'black-hole-powered _',
    '_ awash with slime',
    '_ of bone',
    '_ of blood',
    '_ of flesh',
    'astral _',
    'imploded _',
    'calamitous _',
    '_ wrought of darkness',
    'self-replicating _',
    'AI _',
    'lich _',
    'illusionary _',
    'underworld _',
    '_ where death reigns',
  ],
  10: [
    '_ that eats planets',
    '_ that exists across all space and all time',
    '_ made by a dead god',
    '_ only accessible once every thousand years',
    'subatomic _',
    '_ orbiting a dying sun',
    '_ at the end of the universe',
    'quantum _',
    'infinite _',
    'half-dream _',
    'jovian _',
    'megalithic _',
    'fractal _',
    'psychotropic _',
    '_ that should not be',
    '_ at the heart of a sun',
    'mirror universe _',
    "Galt's _",
  ],
};
